import { EntityManager } from 'typeorm';

import { DEV_SEED_WORKSPACE_MEMBER_IDS } from 'src/database/typeorm-seeds/workspace/workspace-members';

const tableName = 'company';

export const DEV_SEED_COMPANY_IDS = {
  LINKEDIN: '20202020-3ec3-4fe3-8997-b76aa0bfa408',
  FACEBOOK: '20202020-5d81-46d6-bf83-f7fd33ea6102',
  QONTO: '20202020-0713-40a5-8216-82802401d33e',
  MICROSOFT: '20202020-ed89-413a-b31a-962986e67bb4',
  AIRBNB: '20202020-171e-4bcc-9cf7-43448d6fb278',
  GOOGLE: '20202020-c21e-4ec2-873b-de4264d89025',
  NETFLIX: '20202020-707e-44dc-a1d2-30030bf1a944',
  LIBEO: '20202020-3f74-492d-a101-2a70f50a1645',
  CLAAP: '20202020-cfbf-4156-a790-e39854dcd4eb',
  HASURA: '20202020-f86b-419f-b794-02319abe8637',
  WEWORK: '20202020-5518-4553-9433-42d8eb82834b',
  SAMSUNG: '20202020-f79e-40dd-bd06-c36e6abb4678',
  ALGOLIA: '20202020-1455-4c57-afaf-dd5dc086361d',
};

export const seedCompanies = async (
  entityManager: EntityManager,
  schemaName: string,
) => {
  await entityManager
    .createQueryBuilder()
    .insert()
    .into(`${schemaName}.${tableName}`, [
      'id',
      'name',
      'domainNamePrimaryLinkUrl',
      'addressAddressStreet1',
      'addressAddressStreet2',
      'addressAddressCity',
      'addressAddressState',
      'addressAddressPostcode',
      'addressAddressCountry',
      'position',
      'tagline',
      'workPolicy',
      'createdBySource',
      'createdByWorkspaceMemberId',
      'createdByName',
    ])
    .orIgnore()
    .values([
      {
        id: DEV_SEED_COMPANY_IDS.LINKEDIN,
        name: 'Escola São João',
        domainNamePrimaryLinkUrl: 'https://saojohnschool.com',
        addressAddressStreet1: 'Rua das Flores, 150',
        addressAddressStreet2: null,
        addressAddressCity: 'São Paulo',
        addressAddressState: 'SP',
        addressAddressPostcode: '01000-000',
        addressAddressCountry: 'Brasil',
        position: 1,
        tagline: 'Educação de qualidade',
        workPolicy: ['ON_SITE'],
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'João Silva',
      },
      {
        id: DEV_SEED_COMPANY_IDS.FACEBOOK,
        name: 'Colégio Nova Geração',
        domainNamePrimaryLinkUrl: 'https://novageracaoedu.com.br',
        addressAddressStreet1: 'Avenida Brasil, 3000',
        addressAddressStreet2: null,
        addressAddressCity: 'Rio de Janeiro',
        addressAddressState: 'RJ',
        addressAddressPostcode: '20000-000',
        addressAddressCountry: 'Brasil',
        position: 2,
        tagline: 'Formando líderes do amanhã',
        workPolicy: ['REMOTE_WORK', 'ON_SITE'],
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'Ana Costa',
      },
      {
        id: DEV_SEED_COMPANY_IDS.QONTO,
        name: 'Escola Mirante do Saber',
        domainNamePrimaryLinkUrl: 'https://mirantedosaber.edu.br',
        addressAddressStreet1: 'Rua dos Lírios, 75',
        addressAddressStreet2: null,
        addressAddressCity: 'Belo Horizonte',
        addressAddressState: 'MG',
        addressAddressPostcode: '30100-000',
        addressAddressCountry: 'Brasil',
        position: 3,
        tagline: 'Onde o saber floresce',
        workPolicy: ['ON_SITE'],
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'Felipe Souza',
      },
      {
        id: DEV_SEED_COMPANY_IDS.MICROSOFT,
        name: 'Colégio Santa Clara',
        domainNamePrimaryLinkUrl: 'https://santaclaraedu.com',
        addressAddressStreet1: 'Rua do Sol, 230',
        addressAddressStreet2: null,
        addressAddressCity: 'Fortaleza',
        addressAddressState: 'CE',
        addressAddressPostcode: '60000-000',
        addressAddressCountry: 'Brasil',
        position: 4,
        tagline: 'Excelência em ensino',
        workPolicy: ['HYBRID', 'ON_SITE'],
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'Lucas Pereira',
      },
      {
        id: DEV_SEED_COMPANY_IDS.AIRBNB,
        name: 'Escola Futuro Brilhante',
        domainNamePrimaryLinkUrl: 'https://futurobrilhante.edu.br',
        addressAddressStreet1: 'Rua das Acácias, 500',
        addressAddressStreet2: null,
        addressAddressCity: 'Curitiba',
        addressAddressState: 'PR',
        addressAddressPostcode: '80000-000',
        addressAddressCountry: 'Brasil',
        position: 5,
        tagline: 'Transformando o futuro das crianças',
        workPolicy: ['REMOTE_WORK', 'ON_SITE'],
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'Carlos Mendes',
      },
    ])
    .execute();
};
