import { EntityManager } from 'typeorm';

import { DEV_SEED_COMPANY_IDS } from 'src/database/typeorm-seeds/workspace/companies';
import { DEV_SEED_WORKSPACE_MEMBER_IDS } from 'src/database/typeorm-seeds/workspace/workspace-members';

const tableName = 'person';

export const DEV_SEED_PERSON_IDS = {
  CHRISTOPH: '20202020-1c0e-494c-a1b6-85b1c6fefaa5',
  SYLVIE: '20202020-ac73-4797-824e-87a1f5aea9e0',
  CHRISTOPHER_G: '20202020-f517-42fd-80ae-14173b3b70ae',
  ASHLEY: '20202020-eee1-4690-ad2c-8619e5b56a2e',
  NICHOLAS: '20202020-6784-4449-afdf-dc62cb8702f2',
  ISABELLA: '20202020-490f-4466-8391-733cfd66a0c8',
  MATTHEW: '20202020-80f1-4dff-b570-a74942528de3',
  ELIZABETH: '20202020-338b-46df-8811-fa08c7d19d35',
  CHRISTOPHER_N: '20202020-64ad-4b0e-bbfd-e9fd795b7016',
  AVERY: '20202020-5d54-41b7-ba36-f0d20e1417ae',
  ETHAN: '20202020-623d-41fe-92e7-dd45b7c568e1',
  MADISON: '20202020-2d40-4e49-8df4-9c6a049190ef',
  BERTRAND: '20202020-2d40-4e49-8df4-9c6a049190df',
  LOUIS: '20202020-2d40-4e49-8df4-9c6a049191de',
  LORIE: '20202020-2d40-4e49-8df4-9c6a049191df',
};

export const seedPeople = async (
  entityManager: EntityManager,
  schemaName: string,
) => {
  await entityManager
    .createQueryBuilder()
    .insert()
    .into(`${schemaName}.${tableName}`, [
      'id',
      'nameFirstName',
      'nameLastName',
      'phonesPrimaryPhoneCountryCode',
      'phonesPrimaryPhoneCallingCode',
      'phonesPrimaryPhoneNumber',
      'city',
      'companyId',
      'emailsPrimaryEmail',
      'position',
      'whatsappPrimaryPhoneCountryCode',
      'whatsappPrimaryPhoneCallingCode',
      'whatsappPrimaryPhoneNumber',
      'createdBySource',
      'createdByWorkspaceMemberId',
      'createdByName',
    ])
    .orIgnore()
    .values([
      {
        id: DEV_SEED_PERSON_IDS.CHRISTOPH,
        nameFirstName: 'João',
        nameLastName: 'Silva',
        phonesPrimaryPhoneCountryCode: 'BR',
        phonesPrimaryPhoneCallingCode: '+55',
        phonesPrimaryPhoneNumber: '11987654321',
        city: 'São Paulo',
        companyId: DEV_SEED_COMPANY_IDS.LINKEDIN,
        emailsPrimaryEmail: 'joao.silva@saojohnschool.com',
        position: 1,
        whatsappPrimaryPhoneCountryCode: 'BR',
        whatsappPrimaryPhoneCallingCode: '+55',
        whatsappPrimaryPhoneNumber: '11987654321',
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'João Silva',
      },
      {
        id: DEV_SEED_PERSON_IDS.SYLVIE,
        nameFirstName: 'Mariana',
        nameLastName: 'Alves',
        phonesPrimaryPhoneCountryCode: 'BR',
        phonesPrimaryPhoneCallingCode: '+55',
        phonesPrimaryPhoneNumber: '11987654322',
        city: 'São Paulo',
        companyId: DEV_SEED_COMPANY_IDS.LINKEDIN,
        emailsPrimaryEmail: 'mariana.alves@saojohnschool.com',
        position: 2,
        whatsappPrimaryPhoneCountryCode: 'BR',
        whatsappPrimaryPhoneCallingCode: '+55',
        whatsappPrimaryPhoneNumber: '11987654322',
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'João Silva',
      },
      {
        id: DEV_SEED_PERSON_IDS.CHRISTOPHER_G,
        nameFirstName: 'Paulo',
        nameLastName: 'Pereira',
        phonesPrimaryPhoneCountryCode: 'BR',
        phonesPrimaryPhoneCallingCode: '+55',
        phonesPrimaryPhoneNumber: '21987654321',
        city: 'Rio de Janeiro',
        companyId: DEV_SEED_COMPANY_IDS.FACEBOOK,
        emailsPrimaryEmail: 'paulo.pereira@novageracaoedu.com.br',
        position: 1,
        whatsappPrimaryPhoneCountryCode: 'BR',
        whatsappPrimaryPhoneCallingCode: '+55',
        whatsappPrimaryPhoneNumber: '21987654321',
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'Ana Costa',
      },
      {
        id: DEV_SEED_PERSON_IDS.ASHLEY,
        nameFirstName: 'Renata',
        nameLastName: 'Costa',
        phonesPrimaryPhoneCountryCode: 'BR',
        phonesPrimaryPhoneCallingCode: '+55',
        phonesPrimaryPhoneNumber: '21987654322',
        city: 'Rio de Janeiro',
        companyId: DEV_SEED_COMPANY_IDS.FACEBOOK,
        emailsPrimaryEmail: 'renata.costa@novageracaoedu.com.br',
        position: 2,
        whatsappPrimaryPhoneCountryCode: 'BR',
        whatsappPrimaryPhoneCallingCode: '+55',
        whatsappPrimaryPhoneNumber: '21987654322',
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'Ana Costa',
      },
      {
        id: DEV_SEED_PERSON_IDS.NICHOLAS,
        nameFirstName: 'Carlos',
        nameLastName: 'Oliveira',
        phonesPrimaryPhoneCountryCode: 'BR',
        phonesPrimaryPhoneCallingCode: '+55',
        phonesPrimaryPhoneNumber: '31987654321',
        city: 'Belo Horizonte',
        companyId: DEV_SEED_COMPANY_IDS.QONTO,
        emailsPrimaryEmail: 'carlos.oliveira@mirantedosaber.edu.br',
        position: 1,
        whatsappPrimaryPhoneCountryCode: 'BR',
        whatsappPrimaryPhoneCallingCode: '+55',
        whatsappPrimaryPhoneNumber: '31987654321',
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'Felipe Souza',
      },
      {
        id: DEV_SEED_PERSON_IDS.ISABELLA,
        nameFirstName: 'Fernanda',
        nameLastName: 'Souza',
        phonesPrimaryPhoneCountryCode: 'BR',
        phonesPrimaryPhoneCallingCode: '+55',
        phonesPrimaryPhoneNumber: '31987654322',
        city: 'Belo Horizonte',
        companyId: DEV_SEED_COMPANY_IDS.QONTO,
        emailsPrimaryEmail: 'fernanda.souza@mirantedosaber.edu.br',
        position: 2,
        whatsappPrimaryPhoneCountryCode: 'BR',
        whatsappPrimaryPhoneCallingCode: '+55',
        whatsappPrimaryPhoneNumber: '31987654322',
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'Felipe Souza',
      },
      {
        id: DEV_SEED_PERSON_IDS.MATTHEW,
        nameFirstName: 'Amanda',
        nameLastName: 'Mendes',
        phonesPrimaryPhoneCountryCode: 'BR',
        phonesPrimaryPhoneCallingCode: '+55',
        phonesPrimaryPhoneNumber: '41987654321',
        city: 'Curitiba',
        companyId: DEV_SEED_COMPANY_IDS.AIRBNB,
        emailsPrimaryEmail: 'amanda.mendes@futurobrilhante.edu.br',
        position: 1,
        whatsappPrimaryPhoneCountryCode: 'BR',
        whatsappPrimaryPhoneCallingCode: '+55',
        whatsappPrimaryPhoneNumber: '41987654321',
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'Carlos Mendes',
      },
      {
        id: DEV_SEED_PERSON_IDS.ELIZABETH,
        nameFirstName: 'Luciana',
        nameLastName: 'Martins',
        phonesPrimaryPhoneCountryCode: 'BR',
        phonesPrimaryPhoneCallingCode: '+55',
        phonesPrimaryPhoneNumber: '41987654322',
        city: 'Curitiba',
        companyId: DEV_SEED_COMPANY_IDS.AIRBNB,
        emailsPrimaryEmail: 'luciana.martins@futurobrilhante.edu.br',
        position: 2,
        whatsappPrimaryPhoneCountryCode: 'BR',
        whatsappPrimaryPhoneCallingCode: '+55',
        whatsappPrimaryPhoneNumber: '41987654322',
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'Carlos Mendes',
      },
      {
        id: DEV_SEED_PERSON_IDS.CHRISTOPHER_N,
        nameFirstName: 'Roberta',
        nameLastName: 'Nascimento',
        phonesPrimaryPhoneCountryCode: 'BR',
        phonesPrimaryPhoneCallingCode: '+55',
        phonesPrimaryPhoneNumber: '11987654321',
        city: 'Fortaleza',
        companyId: DEV_SEED_COMPANY_IDS.MICROSOFT,
        emailsPrimaryEmail: 'roberta.nascimento@santaclaraedu.com',
        position: 1,
        whatsappPrimaryPhoneCountryCode: 'BR',
        whatsappPrimaryPhoneCallingCode: '+55',
        whatsappPrimaryPhoneNumber: '11987654321',
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'Lucas Pereira',
      },
      {
        id: DEV_SEED_PERSON_IDS.AVERY,
        nameFirstName: 'Fernanda',
        nameLastName: 'Lima',
        phonesPrimaryPhoneCountryCode: 'BR',
        phonesPrimaryPhoneCallingCode: '+55',
        phonesPrimaryPhoneNumber: '11987654322',
        city: 'Fortaleza',
        companyId: DEV_SEED_COMPANY_IDS.MICROSOFT,
        emailsPrimaryEmail: 'fernanda.lima@santaclaraedu.com',
        position: 2,
        whatsappPrimaryPhoneCountryCode: 'BR',
        whatsappPrimaryPhoneCallingCode: '+55',
        whatsappPrimaryPhoneNumber: '11987654322',
        createdBySource: 'MANUAL',
        createdByWorkspaceMemberId: DEV_SEED_WORKSPACE_MEMBER_IDS.TIM,
        createdByName: 'Lucas Pereira',
      },
    ])
    .execute();
};
